name: Polibatam Cyber
url: http://polibatamcyber.tech
twitter: ''
description: |
  Polibatam Cyber is a student led organization at Politenik Batam University that focuses on the technical and social aspects of cyber security

timezone: America/New_York

exclude: ['CNAME']

host: localhost
port: 8080
